I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapters/prologue2.rpy", line 3580, in script
    with Squares(3.00)
  File "game/chapters/prologue2.rpy", line 3580, in <module>
    with Squares(3.00)
NameError: name 'Squares' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapters/prologue2.rpy", line 3580, in script
    with Squares(3.00)
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Brandon H\Desktop\renpy-8.2.3-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/chapters/prologue2.rpy", line 3580, in <module>
    with Squares(3.00)
NameError: name 'Squares' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
Reawakening 1.0
Sun Sep  8 21:31:20 2024
